# Generated by Django 4.2.7 on 2023-11-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery', models.PositiveSmallIntegerField()),
                ('hospital_number', models.PositiveSmallIntegerField()),
                ('age', models.PositiveSmallIntegerField()),
                ('reactal_temp', models.PositiveSmallIntegerField()),
                ('pulse', models.PositiveSmallIntegerField()),
                ('respiratory_rate', models.PositiveSmallIntegerField()),
                ('mucous_membrane', models.PositiveSmallIntegerField()),
                ('capillary_refill_time', models.PositiveSmallIntegerField()),
                ('PendingDeprecationWarningperistalsis', models.PositiveSmallIntegerField()),
                ('abdominal_distention', models.PositiveSmallIntegerField()),
                ('nasogastric_tube', models.PositiveSmallIntegerField()),
                ('nasogastric_reflux', models.PositiveSmallIntegerField()),
                ('nasogastric_reflux_ph', models.PositiveSmallIntegerField()),
                ('rectal_exam_feces', models.PositiveSmallIntegerField()),
                ('abdomen', models.PositiveSmallIntegerField()),
                ('packed_cell_volume', models.PositiveSmallIntegerField()),
                ('total_protein', models.PositiveSmallIntegerField()),
                ('abdomo_appearance', models.PositiveSmallIntegerField()),
                ('abdomo_protein', models.PositiveSmallIntegerField()),
                ('surgical_lesion', models.PositiveSmallIntegerField()),
                ('lesion_1', models.PositiveSmallIntegerField()),
                ('lesion_2', models.PositiveSmallIntegerField()),
                ('lesion_3', models.PositiveSmallIntegerField()),
                ('co_data', models.PositiveSmallIntegerField()),
                ('outcome', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Programmer',
        ),
    ]
