from django.db import models

# Create your models here.

class Surgery(models.Model):
    #surgery = models.CharField(max_length=100)
    surgery = models.PositiveSmallIntegerField()
    hospital_number = models.PositiveSmallIntegerField()
    age= models.PositiveSmallIntegerField()
    reactal_temp= models.PositiveSmallIntegerField()
    pulse= models.PositiveSmallIntegerField()
    respiratory_rate = models.PositiveSmallIntegerField()
    mucous_membrane =models.PositiveSmallIntegerField()
    capillary_refill_time =models.PositiveSmallIntegerField()
    PendingDeprecationWarningperistalsis =models.PositiveSmallIntegerField()
    abdominal_distention =models.PositiveSmallIntegerField()
    nasogastric_tube=models.PositiveSmallIntegerField()
    nasogastric_reflux =models.PositiveSmallIntegerField()
    nasogastric_reflux_ph =models.PositiveSmallIntegerField()
    rectal_exam_feces =models.PositiveSmallIntegerField()
    abdomen =models.PositiveSmallIntegerField()
    packed_cell_volume =models.PositiveSmallIntegerField()
    total_protein =models.PositiveSmallIntegerField()
    abdomo_appearance= models.PositiveSmallIntegerField()
    abdomo_protein =models.PositiveSmallIntegerField()
    surgical_lesion =models.PositiveSmallIntegerField()
    lesion_1=models.PositiveSmallIntegerField()
    lesion_2=models.PositiveSmallIntegerField()
    lesion_3=models.PositiveSmallIntegerField()
    co_data=models.PositiveSmallIntegerField()
    outcome=models.PositiveSmallIntegerField()